name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Download Pluginval
        run: |
          mkdir Pluginval
          cd Pluginval
          curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
          unzip pluginval

      - name: Build Plugin Mac AU & VST3
        run: |
          cd viator-de-noiser/Builds/MacOSX
          xcodebuild -project "viator-de-noiser.xcodeproj" -scheme "viator-de-noiser - All" -configuration Release

      - name: Validate Mac AU
        run: |
          sudo killall -9 AudioComponentRegistrar
          sudo killall -9 coreaudiod
          Pluginval/pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --validate-in-process --verbose --validate ~/Library/Audio/Plug-Ins/Components/viator-de-noiser.component || exit 1

      - name: Validate Mac VST3
        run: |
          sudo killall -9 AudioComponentRegistrar
          sudo killall -9 coreaudiod
          Pluginval/pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --validate-in-process --verbose --validate ~/Library/Audio/Plug-Ins/VST3/viator-de-noiser.vst3 || exit 1

      - name: Delete .a files
        run: rm -R viator-de-noiser/Builds/MacOSX/build/Release/libviator-de-noiser.a

      - name: Sign Mac Builds
        env:
          HASH_OF_DEVELOPER_ID_APPLICATION: ${{ secrets.HASH_OF_DEVELOPER_ID_APPLICATION }}
        run: |
          codesign --deep --force --options=runtime --sign "$HASH_OF_DEVELOPER_ID_APPLICATION" --timestamp ~/Library/Audio/Plug-Ins/Components/viator-de-noiser.component
          codesign --deep --force --options=runtime --sign "$HASH_OF_DEVELOPER_ID_APPLICATION" --timestamp ~/Library/Audio/Plug-Ins/VST3/viator-de-noiser.vst3

      - name: Upload Mac AU
        uses: actions/upload-artifact@v3
        with:
          name: Mac-viator-de-noiser-AU-Artifact
          path: ~/Library/Audio/Plug-Ins/Components/

      - name: Upload Mac VST3
        uses: actions/upload-artifact@v3
        with:
          name: Mac-viator-de-noiser-VST3-Artifact
          path: ~/Library/Audio/Plug-Ins/VST3/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "latest"

      - name: Download Pluginval
        run: |
          mkdir Pluginval
          cd Pluginval
          curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Windows.zip" -o pluginval.zip
          Expand-Archive -Path pluginval.zip -DestinationPath . -Force

      - name: Build Plugin Windows VST3
        run: |
          cd viator-de-noiser/Builds/VisualStudio2022
          msbuild "viator-de-noiser.sln" /p:Configuration=Release /p:Platform=x64

      - name: Validate Windows VST3
        run: |
          Pluginval\pluginval.exe --strictness-level 5 --validate-in-process --verbose --validate viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser.vst3 || exit 1

      - name: Delete useless Windows files
        run: |
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\resources.res
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-v.4FC9B7FB.tlog
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser.exp
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser.iobj
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser.pdb
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser.vst3.recipe
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser_VST3.log
          rm -R viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\viator-de-noiser_VST3.vcxproj.FileListAbsolute.txt

      - name: Upload Windows VST3
        uses: actions/upload-artifact@v3
        with:
          name: Windows-viator-de-noiser-VST3-Artifact
          path: viator-de-noiser\Builds\VisualStudio2022\x64\Release\VST3\
