name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache Projucer build
        uses: actions/cache@v2
        with:
          path: modules/JUCE/extras/Projucer/Builds/MacOSX/build
          key: ${{ runner.os }}-projucer-${{ hashFiles('modules/JUCE/extras/Projucer/Builds/MacOSX/Projucer.xcodeproj') }}

      - name: Build Projucer
        run: |
          cd modules/JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj -scheme "Projucer - App" -configuration Release
          cp -R build/Release/Projucer.app builds/
