name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #build:
  #runs-on: macos-latest

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "latest"

      # - name: Build Projucer
      #  run: |
      #    cd modules/JUCE/extras/Projucer/Builds/VisualStudio2019
      #    msbuild Projucer.sln /p:Configuration=Release /p:Platform=x64

      # - name: Save Projucer Project
      #   run: |
      #     modules\JUCE\extras\Projucer\Builds\VisualStudio2019\x64\Release\App\Projucer.exe --resave viator-voice-sweetener\"viator-voice-sweetener.jucer"

      - name: Download Pluginval
        run: |
          mkdir Pluginval
          cd Pluginval
          curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Windows.zip" -o pluginval.zip
          Expand-Archive -Path pluginval.zip -DestinationPath . -Force

      - name: Build Plugin Windows VST3
        run: |
          cd viator-voice-sweetener/Builds/VisualStudio2019
          msbuild "viator-voice-sweetener.sln" /p:Configuration=Release /p:Platform=x64
          echo "Current Directory: $PWD"
        # copy "x86/Release/VST3/viator-voice-sweetener.vst3" "C:\Program Files (x86)\Common Files\VST3\"

      - name: Validate Windows VST3
        run: |
          Pluginval\pluginval.exe --strictness-level 5 --validate-in-process --verbose --validate "C:\Program Files (x86)\Common Files\VST3\viator-voice-sweetener.vst3" || exit 1

      - name: Upload Windows VST3
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Hermes-Voice-EQ-VST3-Artifact
          path: "C:/Program Files (x86)/Common Files/VST3/"
